REM CHOOSE A COLOR FOR THE "BALL"
BALL=9

REM SET GRAPHICS MODE
GR

REM CHOOSE A STARTING POSITION FOR THE BALL
XOLD=20

REM MOVE THE BALL BACK AND FORTH BY ADDING AN INCREMENT (CALLED XSPEED) TO THE X POSITION
REM TO MOVE THE BALL TO THE LEFT, MAKE THE INCREMENT NEGATIVE
XSPEED=1

REM CALCULATE THE NEW X POSITION BY ADDING THE INCREMENT XSPEED TO THE OLD X POSITION
<CALC_NEW_X> XNEW=XOLD+XSPEED

REM CHECK THAT THE BALL WOULD BE ON THE SCREEN
IF (XNEW>-1) AND (XNEW<40) THEN GOTO @PLOT

REM THE BALL WOULD BE OFF THE SIDE OF THE SCREEN< SO CHANGE THE DIRECTION OF X MOTION
XSPEED=-1*XSPEED
GOTO @CALC_NEW_X

REM PLOT THE BALL IN ITS NEW POSITION
<PLOT> COLOR=BALL
PLOT XNEW,20

REM ERASE THE OLD BALL POSITION
COLOR=0
PLOT XOLD,20

REM SAVE THE CURRENT BALL POSITION FOR THE NEXT MOVE
XOLD=XNEW

REM MOVE AGAIN
GOTO @CALC_NEW_X
